# Copyright (C) 2026 Settlers Freaks <sf-team at siedler25.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# CI for s25edit.

name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ format('s25edit-{0}:{1}', github.repository, github.ref) }}
  cancel-in-progress: true

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install REUSE
        run: |
          pip install --user reuse

      - name: Formatting
        uses: DoozyX/clang-format-lint-action@c71d0bf4e21876ebec3e5647491186f8797fde31 # v0.18.2
        with:
          source: "."
          clangFormatVersion: 10

      - name: Check include guards (#pragma once)
        run: |
          find . -path ./.git -prune -false \
            -o -path ./build -prune -false \
            -o -path ./SGE -prune -false \
            -o \( -name '*.hpp' -o -name '*.h' \) \
            -print0 | xargs -0 -n1 tools/ci/checkIncludeGuards.sh

      - name: Check licensing (REUSE)
        run: reuse lint
